export const PAINTER_STYLES = [
  { id: 'default', name: 'Default (Clean)', class: '' },
  { id: 'van-gogh', name: 'Vincent van Gogh', class: 'theme-van-gogh' },
  { id: 'monet', name: 'Claude Monet', class: 'theme-monet' },
  { id: 'picasso', name: 'Pablo Picasso', class: 'theme-picasso' },
  { id: 'da-vinci', name: 'Leonardo da Vinci', class: 'theme-da-vinci' },
  { id: 'dali', name: 'Salvador Dali', class: 'theme-dali' },
  { id: 'munch', name: 'Edvard Munch', class: 'theme-munch' },
  { id: 'klimt', name: 'Gustav Klimt', class: 'theme-klimt' },
  { id: 'vermeer', name: 'Johannes Vermeer', class: 'theme-vermeer' },
  { id: 'kahlo', name: 'Frida Kahlo', class: 'theme-kahlo' },
  { id: 'pollock', name: 'Jackson Pollock', class: 'theme-pollock' },
  { id: 'warhol', name: 'Andy Warhol', class: 'theme-warhol' },
  { id: 'okeeffe', name: "Georgia O'Keeffe", class: 'theme-okeeffe' },
  { id: 'matisse', name: 'Henri Matisse', class: 'theme-matisse' },
  { id: 'degas', name: 'Edgar Degas', class: 'theme-degas' },
  { id: 'rembrandt', name: 'Rembrandt', class: 'theme-rembrandt' },
  { id: 'botticelli', name: 'Sandro Botticelli', class: 'theme-botticelli' },
  { id: 'renoir', name: 'Pierre-Auguste Renoir', class: 'theme-renoir' },
  { id: 'kandinsky', name: 'Wassily Kandinsky', class: 'theme-kandinsky' },
  { id: 'mondrian', name: 'Piet Mondrian', class: 'theme-mondrian' },
  { id: 'hokusai', name: 'Katsushika Hokusai', class: 'theme-hokusai' },
];
